In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/iriscsv/Iris.csv


### Iris Dataset Description

The Iris dataset is one of the most famous datasets in machine learning. It contains **150 samples of Iris flowers**, divided into **3 species**:
- **Iris-setosa**
- **Iris-versicolor**
- **Iris-virginica**

Each sample has **4 features (measurements)**:
1. **Sepal length (cm)**
2. **Sepal width (cm)**
3. **Petal length (cm)**
4. **Petal width (cm)**

The goal is to use these measurements to **classify the species** of each flower.


# Step_1. Import libraries

In [2]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import sklearn

In [3]:
import warnings 
warnings.filterwarnings('ignore')

# Step_2. Load the dataset

In [4]:
df=pd.read_csv('/kaggle/input/iriscsv/Iris.csv')

# Step_3. Descriptive statistical analysis of dataset

In [5]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [6]:
df.shape

(150, 6)

In [7]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [9]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

# Step_4. Data Preprocessing

In [10]:
# Drop irrelevant features 
df.drop(columns=['Id'], inplace=True)

In [11]:
df.columns

Index(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

# Step_5. Feature Selection

In [12]:
# Features
X = df[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]
# Target Veriable
y = df['Species']

In [13]:
X.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [14]:
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object

# Step_6. Training a Model

In [15]:
# Train test spilt
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.20, random_state = 42)
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [16]:
# Training the KNN Model
from sklearn import neighbors
model = neighbors.KNeighborsClassifier(n_neighbors = 3)

In [17]:
# Train the Model
model.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [18]:
# Prediction
y_pred = model.predict(X_test)

# Step_7. Evaluation

In [19]:
# Evaluation
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

1.0
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


# KNN Model Evaluation Report

The KNN model predicted the species of Iris flowers with **100% accuracy** on the test data.

- **Precision, Recall, and F1-score** are all **1.00** for every flower type (Setosa, Versicolor, Virginica), meaning the model made no mistakes.
- **Accuracy = 100%**, which means all 30 flowers in the test set were correctly classified.
- The **confusion matrix** shows that:
  - All 10 Setosa, 9 Versicolor, and 11 Virginica flowers were predicted correctly.
- This result indicates that the model is performing perfectly for this dataset.
